# Generated by Django 2.1.6 on 2019-02-27 21:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20190211_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaricaSociale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaricaCode', models.TextField(default='S')),
                ('CaricaDescrizione', models.TextField(default='Socio')),
            ],
            options={
                'verbose_name': 'CaricaSociale',
                'verbose_name_plural': 'CaricheSociali',
            },
        ),
        migrations.CreateModel(
            name='Discussione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=120)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discussione',
                'verbose_name_plural': 'Discussioni',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Rcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inizio', models.DateTimeField()),
                ('Fine', models.DateTimeField()),
                ('CaricaSociale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CaricaSociale')),
            ],
            options={
                'verbose_name': 'RelazioneCarica',
                'verbose_name_plural': 'RelazioniCariche',
            },
        ),
        migrations.CreateModel(
            name='Rts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'RelazioneTessere',
                'verbose_name_plural': 'RelazioniTessere',
            },
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sezione', models.CharField(max_length=80)),
                ('descrizione', models.CharField(blank=True, max_length=150, null=True)),
                ('logo_sezione', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('descrizione', models.CharField(blank=True, max_length=150, null=True)),
                ('foto_socio', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Soci',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tessera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TesseraId', models.CharField(max_length=15)),
                ('TesseraNumero', models.CharField(max_length=15)),
                ('TesseraRilascioIl', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tessera',
                'verbose_name_plural': 'Tessere',
            },
        ),
        migrations.AddField(
            model_name='rts',
            name='SocioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Socio'),
        ),
        migrations.AddField(
            model_name='rts',
            name='TesseraId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni', to='core.Tessera'),
        ),
        migrations.AddField(
            model_name='rcs',
            name='SocioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Socio'),
        ),
        migrations.AddField(
            model_name='post',
            name='autore_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='discussione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Discussione'),
        ),
        migrations.AddField(
            model_name='discussione',
            name='autore_discussione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussione',
            name='sezione_appartenenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sezione'),
        ),
    ]
