# Generated by Django 2.1.6 on 2019-02-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relazione',
                'verbose_name_plural': 'Relazioni',
            },
        ),
        migrations.CreateModel(
            name='Tessera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TesseraId', models.CharField(max_length=15)),
                ('TesseraNumero', models.CharField(max_length=15)),
                ('TesseraRilascioIl', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tessera',
                'verbose_name_plural': 'Tessere',
            },
        ),
        migrations.AddField(
            model_name='rts',
            name='Sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tessera'),
        ),
        migrations.AddField(
            model_name='rts',
            name='Tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni', to='core.Socio'),
        ),
    ]
