# Generated by Django 2.1.6 on 2019-02-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rts',
            name='Sid',
        ),
        migrations.RemoveField(
            model_name='rts',
            name='Tid',
        ),
        migrations.DeleteModel(
            name='Rts',
        ),
    ]
