# Generated by Django 2.1.6 on 2019-02-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190211_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tessera')),
                ('TesseraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni', to='core.Socio')),
            ],
            options={
                'verbose_name': 'Relazione',
                'verbose_name_plural': 'Relazioni',
            },
        ),
    ]
